[tool.poetry]
name = "docint"
version = "0.1.0"
description = "Extracting information from documents intelligently (docInt) !"
authors = ["Mukund Desh <mukundesh@outlook.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
black = "^21.11b1"
pytest = "^6.2.5"
PyYAML = "^6.0"
pytesseract = "^0.3.8"
google-cloud-vision = "^2.6.3"
google-cloud-storage = "^1.44.0"
pdfplumber = "^0.6.0"
pdf2image = "^1.16.0"
pydantic = "^1.9.0"
jsview = "^1.2"
pyenchant = "^3.2.2"
rich = "^11.2.0"
python-dateutil = "^2.8.2"
more-itertools = "^8.12.0"
msgpack = "^1.0.3"
polyleven = "^0.7"
numpy = "<1.22.0"
opencv-python = "^4.4.0.46"
mkdocs = "^1.3.0"
mkdocs-include-markdown-plugin = "^3.5.2"
mkdocs-material = "^8.3.9"
mkdocstrings = {extras = ["python"], version = "^0.19.0"}
mkdocs-material-extensions = "^1.0.3"
mkdocs-autorefs = "^0.4.1"
flake8 = "^3.9.2"
mkdocs-gen-files = "^0.3.5"
mkdocs-literate-nav = "^0.4.1"
mkdocs-section-index = "^0.3.4"

[tool.poetry.dev-dependencies]
coverage = "^6.3.1"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
