[tool.poetry]
name = "docint"
version = "0.1.0"
description = "Extracting information from documents intelligently (docInt) !"
authors = ["Mukund Desh <mukundesh@outlook.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
flake8 = "^4.0.1"
black = "^21.11b1"
pytest = "^6.2.5"
PyYAML = "^6.0"
pytesseract = "^0.3.8"
google-cloud-vision = "^2.6.3"
google-cloud-storage = "^1.44.0"
pdfplumber = "^0.6.0"
pdf2image = "^1.16.0"
pydantic = "^1.9.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
