[tool.poetry]
name = "docint"
version = "0.1.0"
description = "Extracting information from documents intelligently (docInt) !"
authors = ["Mukund Desh <mukundesh@outlook.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
flake8 = "^4.0.1"
black = "^21.11b1"
pytest = "^6.2.5"
PyYAML = "^6.0"
pytesseract = "^0.3.8"
google-cloud-vision = "^2.6.3"
google-cloud-storage = "^1.44.0"
pdfplumber = "^0.6.0"
pdf2image = "^1.16.0"
pydantic = "^1.9.0"
jsview = "^1.2"
pyenchant = "^3.2.2"
rich = "^11.2.0"
python-dateutil = "^2.8.2"
more-itertools = "^8.12.0"
msgpack = "^1.0.3"
opencv-python = "^4.5.5"

[tool.poetry.dev-dependencies]
coverage = "^6.3.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
